site_name: Predator
site_url: http://predator-ng.com
repo_url: https://github.com/Zooz/predator
edit_uri: https://github.com/Zooz/predator/blob/master/docs/devguide/docs/
site_description: Next generation distributed open source performance testing platform for APIs
site_author: ZOOZ
google_analytics: ['UA-40865650-2', 'predator-ng.com']

nav:
  - About: index.md
  - Installation: installation.md
  - My First Test: myfirsttest.md
  - Advanced Test Setup: tests.md
  - Schedules and Reports: schedulesandreports.md
  - Configuration: configuration.md
  - Contributing: contributing.md
  - API Reference: apireference.md

theme:
   name: windmill
   custom_dir: 'mkdocs-windmill/mkdocs_windmill'

use_directory_urls: False

markdown_extensions:
   - codehilite:
       css_class: codehilite
   - pymdownx.superfences:
   - pymdownx.details:
   - admonition
   - sane_lists
   - fenced_code
   - toc:
       permalink: '#'

extra:
    version: 1.0
    logo: logo.png
